Remove old IE workaround
w3c/wai-tutorials pull request #690
Opened 2022-09-11 13:05 UTC by yatil

I guess this wasn’t needed since IE9?

2022-09-12 00:26 UTC, brianelton requested changes

2022-09-12 00:26 UTC, brianelton commented on content/forms/instructions.md
> -<label id="expLabel" for="expire" tabindex="-1">Expiration date:</label>
We should probably remove this from the actual code as well (lines 147 and 150)

2022-09-21 20:41 UTC, shawna-slh commented
@brianelton & @yatil If you both agree and think it does not need any more review, then @brianelton please submit the changes for publication. Thanks!

2022-09-22 12:10 UTC, brianelton approved these changes

2022-09-22 12:11 UTC, merged

2022-09-22 12:11 UTC, brianelton commented
@shawna-slh a fix still needs to be made, but can be done separately and won't affect the core of this change