[IN-PROGRESS] German - An alt Decision Tree
w3c/wai-tutorials pull request #741
Opened 2023-12-22 16:21 UTC by alexejrotar

open questions:
1. Sometimes english words make more sense (or are more common) even in german. For instance, I did not translate the word 'icon'. Should I wrap such words/terms in `span`s with a according `lang` attribute?
2. In german, most words referring to persons are gendered. E.g. the word 'user' is translated to either 'Nutzer' or 'Nutzerin'. The same goes for the articles, 'der' or 'die', respectively. In cases where the gender is unknown or irrelevant (as is mostly the case here), people used to use the male version as neutral. But now there is an ongoing effort to introduce gender-neutral forms to make the language more inclusive. They sort of combine both forms, such as 'Nutzer*in', 'Nutzer:in', 'Nutzer_in', or 'NutzerIn'. I think, a more inclusive language is important and so I used the form 'Nutzer:in' (for no particular reason). Not everyone might agree though, so a discussion about the proper translation of gendered words might be useful for consistency across the translations.

2023-12-22 16:35 UTC, alexejrotar commented
Not sure why the checks fail, can't find anything in the logs. Any ideas?

2023-12-22 18:14 UTC, brianelton commented
> Not sure why the checks fail, can't find anything in the logs. Any ideas?

There are some odd general build issues, but it looks like the preview is working well, so no worries.

2023-12-22 18:33 UTC, shawna-slh commented
> Not sure why the checks fail, can't find anything in the logs. Any ideas?

Sorry, it's a known issue. We have two builds and one works and the other doesn't. We just haven't gotten to clean that up yet.

It's all fine and preview is at: https://deploy-preview-741--wai-tutorials2.netlify.app/tutorials/images/decision-tree/de

2023-12-22 18:34 UTC, shawna-slh commented
assigning @remibetin for the open questions, and he will bring to me what I can help with :-)

2024-01-02 16:02 UTC, remibetin commented
Thank you very much @alexejrotar for this translation of a very popular resource!

> Sometimes english words make more sense (or are more common) even in german. For instance, I did not translate the word 'icon'. Should I wrap such words/terms in spans with a according lang attribute?

I have some preliminary questions/remarks:
- If commonly used in German, is is still considered by most people an "English-language term"?
- Have you considered "Symbole/Symbolen"? Or would you say it is not appropriate in this context?
I say so because I have seen it used to translate "icon/icons" in the [WCAG 2.1 Unofficial translation into German](https://outline-rocks.github.io/wcag/translations/WCAG21-de/#bestimmung-des-zwecks) or in [this documentation page from Apple](https://support.apple.com/de-de/guide/iphone/iphef7bb57dc/ios)
Please note German is not my native language so feel free to consider these remarks as naive and possibly invalid. 

> Gender-neutral language

I will get back to you later on this.

2024-01-04 17:10 UTC, alexejrotar commented
> I have some preliminary questions/remarks:
> 
> * If commonly used in German, is is still considered by most people an "English-language term"?
> * Have you considered "Symbole/Symbolen"? Or would you say it is not appropriate in this context?
>   I say so because I have seen it used to translate "icon/icons" in the [WCAG 2.1 Unofficial translation into German](https://outline-rocks.github.io/wcag/translations/WCAG21-de/#bestimmung-des-zwecks) or in [this documentation page from Apple](https://support.apple.com/de-de/guide/iphone/iphef7bb57dc/ios)

*Short version*
I prefer "Icon" but I guess "Symbol" should be fine.

*Long version*
It's not a naive remark, I guess this is a subtle question, as indicated by the fact that the resources you linked to translate it like this. "Symbol" in german is pretty much the translation for symbol in english and I guess you wouldn't normally use symbol and icon interchangeably. "Icon" in german is used exclusively for digital icons. When talking about web design, I would always use it rather then "Symbol" but that might be a personal preference. At least it's so common that there is a Wikipedia entry in german about icons and also a Duden entry (german dictionary). Still, people would recognize it as an english word an pronounce it as such. Not sure how a screen reader would pronounce it though.. Maybe others feel different about it. I guess "Symbol" would be alright and people would know what you mean.

2024-01-15 15:55 UTC, remibetin commented
> In german, most words referring to persons are gendered. E.g. the word 'user' is translated to either 'Nutzer' or 'Nutzerin'. 

Gender-neutral forms are indeed preferable. That being said, it is important to use forms that most readers are familiar with; and that are easy to read and understand, since readability is a WCAG guideline.

We plan to update the original version to use the plural form "users". Would the use of the plural in German help in this instance?

2024-01-16 18:33 UTC, alexejrotar commented
> Would the use of the plural in German help in this instance?

Unfortunately, no. Plurals are also gendered - "die Nutzer" is the male plural, "die Nutzerinnen" is the female plural. So one convention is to write "Nutzer*innen".

> That being said, it is important to use forms that most readers are familiar with; and that are easy to read and understand, since readability is a WCAG guideline.

That bothered me as well, so I looked into accessible and gender-neutral language. From the few articles that I read about it, it seems that the gender-neutral forms are not considered accessible because they (intentionally) disrupt the flow and because they are read in an awkward way when using a screenreader. Some recommendations that I found said to use both forms, which can be often seen in recent texts, e.g "Nutzerinnen und Nutzer" to refer to users. That is a) somewhat verbose, and b) still excludes non-binary people. Still, I can see now that using the asterisk version is not a good idea, so I would change that. Not quite sure how, though. Hope some german speakers can add their thoughts..

2024-03-02 12:54 UTC, j9t commented
Hi @alexejrotar, @remibetin—I quickly went through the translation. Overall LGTM (can share some smaller suggestions later), but there’s one bigger theme—many terms are separated even though they need to be written together. For example, it should be “`alt`-Entscheidungsbaum,” “`alt`-Attribut”, “`img`-Element”, as these form single nouns in German. I cannot find an exception in [Duden grammar rules](https://www.duden.de/sprachwissen/rechtschreibregeln/getrennt-und-zusammenschreibung) (“Die Bestandteile von Zusammensetzungen werden zusammengeschrieben”).

Can you review and update the translation accordingly?

Rémi, I couldn’t yet check but I imagine this to be an issue in other W3C translations, too. To avoid inconsistencies this probably needs documentation and review. (I believe we touched on this earlier but it may have been in GitHub, and not in email, where I couldn’t find it again.)

2024-03-04 10:09 UTC, remibetin commented
> Rémi, I couldn’t yet check but I imagine this to be an issue in other W3C translations, too. To avoid inconsistencies this probably needs documentation and review. (I believe we touched on this earlier but it may have been in GitHub, and not in email, where I couldn’t find it again.)

I recommend that you to open a Pull Request to edit the German glossary: https://github.com/w3c/translation-glossaries/blob/main/Deutsch-German.md.  Make sure to include the rationale behind this, so that others can eventually add their input.

2024-03-10 13:54 UTC, alexejrotar commented
Thanks for review @j9t. Indeed, I didn't pay much attention to this. I will fix this.

2024-03-12 20:55 UTC, D-oro commented on content/images/decision-tree.de.md
> +      _Nutzen sie das `alt`-Attribut, um die Funktion des Bildes zu kommunizieren. Siehe [Funktionale Bilder](/tutorials/images/functional/)._
Small typo: Should be capital "S" for "Sie"

```suggestion
      _Nutzen Sie das `alt`-Attribut, um die Funktion des Bildes zu kommunizieren. Siehe [Funktionale Bilder](/tutorials/images/functional/)._
```

2024-03-12 21:18 UTC, D-oro commented on content/images/decision-tree.de.md
> +- **Ist das Bild rein dekorativ oder nicht für Nutzerinnen und Nutzer gedacht?**
There is a neutral plural alternative to Nutzerinnen und Nutzer: Nutzende. 
If you look at UX publications in German you see this term in use. 

This does highlight the need for a consensus in the glossary. 
I would like to suggest to follow [the lead of Germanys federal anti-discrimination agency](https://www.antidiskriminierungsstelle.de/SharedDocs/aktuelles/DE/2023/20230227_Genderstern.html) as they highlight both the gender and accessibility concerns related to gender inclusive language. 
The summary is: Use a neutral plural (e.g. "Nutzende") or the asterisk ("Nutzer*in").

```suggestion
- **Ist das Bild rein dekorativ oder nicht für Nutzende gedacht?**
```

2024-03-12 21:44 UTC, D-oro commented on content/images/decision-tree.de.md
> +Dieser Entscheidungsbaum beschreibt, wie man das `alt`-Attribut des `img`-Elements in verschiedenen Situationen verwendet. Für manche Arten von Bildern gibt es Alternativen, etwa CSS-Hintergrundbilde
I'm not sure about this one, but I saw that both the english and [french version](https://deploy-preview-725--wai-tutorials2.netlify.app/tutorials/images/decision-tree/fr)(not yet reviewed) are using the pointy brackets for the html  img element.

```suggestion
Dieser Entscheidungsbaum beschreibt, wie man das `alt`-Attribut des `<img>`-Elements in verschiedenen Situationen verwendet. Für manche Arten von Bildern gibt es Alternativen, etwa CSS-Hintergrundbilder für dekorative Bilder oder Webfonts anstelle von Bildern von Text.
```

2024-03-12 21:57 UTC, D-oro commented
That's my review completed :) Happy to discuss further as needed.

2024-03-13 19:42 UTC, j9t requested changes

2024-03-13 19:42 UTC, j9t commented on content/images/decision-tree.de.md
> +title: "Ein alt Entscheidungsbaum"
Consistent: “Ein alt-Entscheidungsbaum”

2024-03-13 19:42 UTC, j9t commented on content/images/decision-tree.de.md
> +title_html: "Ein <code>alt</code> Entscheidungsbaum"
Consistent, dto.—add hyphen

2024-03-13 19:42 UTC, j9t commented on content/images/decision-tree.de.md
> +  - name: "Alexej Rotar"
(Note for later—could include reviewers?)

2024-03-13 19:42 UTC, j9t commented on content/images/decision-tree.de.md
> +    -   **… und der Text im Bild ist ansonsten nicht vorhanden.** _Nutzen Sie das `alt`-Attribut, um den Text aus dem Bild zu wiederholen. Siehe [Bilder von Text](/tutorials/images/textual/#styled-te
May be clearer: “… und der Text im Bild wird sonst nirgends verwendet.”

2024-03-13 19:42 UTC, j9t commented on content/images/decision-tree.de.md
> +- **Trägt das Bild zur Bedeutung der aktuellen Seite oder des aktuellen Kontexts bei?**
May read nicer: ”des aktuellen Zusammenhangs”

2024-03-13 19:42 UTC, j9t commented on content/images/decision-tree.de.md
> +    - **… und es ist ein Graph oder komplexe Information.**
Suggesting “oder komplexe Informationen werden dargestellt”

2024-03-13 19:42 UTC, j9t commented on content/images/decision-tree.de.md
> +  - {:.yes} Dieser Entscheidungsbaum deckt **nicht alle** Fälle ab. Für detailierte Informationen über die Bereitstellung von Textalternativen, sehen Sie sich die [Seite zu Bildkonzepten](/tutorials/
Instead of “sehen Sie sich […] an”, suggesting “beachten Sie”

2024-03-14 10:03 UTC, remibetin commented on content/images/decision-tree.de.md
> +Dieser Entscheidungsbaum beschreibt, wie man das `alt`-Attribut des `img`-Elements in verschiedenen Situationen verwendet. Für manche Arten von Bildern gibt es Alternativen, etwa CSS-Hintergrundbilde
@D-oro +1

2024-03-14 10:05 UTC, remibetin commented on content/images/decision-tree.de.md
> +  - name: "Alexej Rotar"
@j9t I will indeed add the reviewers in a `contributors` variable before publishing.

2024-03-14 10:20 UTC, remibetin commented on content/images/decision-tree.de.md
> +- **Ist das Bild rein dekorativ oder nicht für Nutzerinnen und Nutzer gedacht?**
Thanks @D-oro for this added context and suggestion.

@alexejrotar @j9t What do you think?

2024-03-14 13:03 UTC, j9t commented on content/images/decision-tree.de.md
> +- **Ist das Bild rein dekorativ oder nicht für Nutzerinnen und Nutzer gedacht?**
I like the spirit of the suggestion, but it doesn’t read well to me. Would prefer whatever is the W3C’s German standard form of “users.”

2024-03-19 14:18 UTC, remibetin commented on content/images/decision-tree.de.md
> +  - name: "Alexej Rotar"
@j9t @D-oro Done: I have added your names in the contributors list. Thanks!

2024-03-21 15:23 UTC, alexejrotar commented on content/images/decision-tree.de.md
> +- **Ist das Bild rein dekorativ oder nicht für Nutzerinnen und Nutzer gedacht?**
Of all the suggested forms, I prefer @D-oro's "Nutzende". Even though it does not sound great to me, it a) includes all genders, in contrast to "Nutzerinnen und Nutzer" or even just "Nutzer", is b) shorter than "Nutzerinnen und Nutzer" and c) I guess is more accessible than "Nutzer*innen". I tend to accept the suggestion. As for the W3C's standard form of "users" - I don't know what it is, feel free to share relevant resources.

2024-03-21 15:34 UTC, alexejrotar commented on content/images/decision-tree.de.md
> +    -   **… und der Text im Bild ist ansonsten nicht vorhanden.** _Nutzen Sie das `alt`-Attribut, um den Text aus dem Bild zu wiederholen. Siehe [Bilder von Text](/tutorials/images/textual/#styled-te
Not sure about the word "verwendet" in this context. in the english version it says: "... and the text in the image is not present otherwise". Maybe something like "... und der Text im Bild kommt sonst nirgends vor"?

2024-03-21 15:37 UTC, alexejrotar commented on content/images/decision-tree.de.md
> +    - **… und es ist ein Graph oder komplexe Information.**
Sounds good to me. Just for reference, this is what the english version says:  "... and it’s a graph or complex piece of information." Not sure, if this "graph" part may be relevant, @remibetin ?

2024-03-21 15:42 UTC, alexejrotar commented
Thanks @j9t and @D-oro for the reviews! I integrated most of your feedback, only two comments remain unresolved. Happy to discuss them further.

2024-03-25 16:02 UTC, remibetin commented on content/images/decision-tree.de.md
> +    - **… und es ist ein Graph oder komplexe Information.**
@alexejrotar Is it indeed important to keep the "graph" part.

2024-03-25 16:09 UTC, remibetin commented
Thanks @alexejrotar! 

@D-oro @j9t Can you take a look at https://github.com/w3c/wai-tutorials/pull/741#discussion_r1534161751 & https://github.com/w3c/wai-tutorials/pull/741#discussion_r1534157438 in case you have any final comments?

We are nearly ready to publish this new translation!

2024-03-25 16:16 UTC, j9t commented
Hi @remibetin—would love to, unfortunately in the middle of a move right now (my availability would only be better starting next week). Wouldn’t want to hold anything up, so if @D-oro has a chance to review I hope that works.

2024-03-25 16:20 UTC, remibetin commented
@j9t Thanks for your reply and much appreciated suggestion. That would indeed work. I wish you a good move!

2024-03-25 19:59 UTC, D-oro commented on content/images/decision-tree.de.md
> +    -   **… und der Text im Bild ist ansonsten nicht vorhanden.** _Nutzen Sie das `alt`-Attribut, um den Text aus dem Bild zu wiederholen. Siehe [Bilder von Text](/tutorials/images/textual/#styled-te
I think "... und der Text im Bild kommt sonst nirgends vor" is good.

2024-03-25 20:03 UTC, D-oro commented on content/images/decision-tree.de.md
> +    - **… und es ist ein Graph oder komplexe Information.**
Here's my recommendation:
"... und es ist ein Graph oder stellt komplexe Informationen dar"

2024-03-26 08:53 UTC, remibetin commented
Thank you @D-oro for your review! cc @alexejrotar

2024-04-07 10:32 UTC, alexejrotar commented
Sorry for not replying for a while. I'm on a trip where i barely have any connection. I also don't have my notebook, so I won't be able to integrate the changes until I return in the end of april. If you want it integrated earlier, feel free to commit the suggested changes for the remaining unresolved comments. I like the suggestions. Thanks @D-oro and @j9t!

2024-04-08 08:39 UTC, remibetin commented
@alexejrotar I have applied the suggestions.

Thank you all for your collaborative work on this translation! cc @D-oro @j9t

2024-04-08 15:34 UTC, shawna-slh commented
Thank you to everyone who contributed to this!

2024-04-08 15:34 UTC, merged

2024-04-08 15:57 UTC, remibetin commented
QA done: ✅