[Japanese] Create decision-tree.ja.md
w3c/wai-tutorials pull request #752
Opened 2024-02-23 05:28 UTC by hiroya-uga

Resolves
- w3c/wai-translations#166

2024-02-23 05:59 UTC, hiroya-uga reviewed
@remibetin I have worked on it! Could you please check it?

2024-02-23 05:59 UTC, hiroya-uga commented on content/images/decision-tree.ja.md
> +title_html: "代替テキスト決定木"
![ask](https://img.shields.io/badge/review-ask-blue.svg)

The original text contains "alt" as a code in the title, but I think it should be called as "An alternative text decision tree" in Japanese.

2024-02-23 05:59 UTC, hiroya-uga commented on content/images/decision-tree.ja.md
> +  - name: "Uga, Hiroya"
![ask](https://img.shields.io/badge/review-ask-blue.svg)

Which do you prefer Hiroya UGA or Uga,Hiroya?

2024-02-23 05:59 UTC, hiroya-uga commented on content/images/decision-tree.ja.md
> +  - {:.yes} この決定木はすべてのケースをカバー**しているわけではありません**。代替テキストの提供に関する詳細については、「[画像に関する概念ページ](/tutorials/images/)」を参照してください。
![ask](https://img.shields.io/badge/review-ask-blue.svg)

The original text says "Image Concepts Page" in the link text, but the destination of the link was actually "Images Tutorial". 
Do you know why the text here is different from the actual page name?

2024-02-26 15:28 UTC, remibetin requested changes
Thanks very much @hiroya-uga for this new translation!

I have added some initial comments for you to consider, with the help of an automatic translation tool.

I will now ask some native Japanese reviewers if they can add their comments. If you know some people that might be willing to help, you can also let me know by email.

2024-02-26 15:28 UTC, remibetin commented on content/images/decision-tree.ja.md
> +    - **かつ、画像内のテキストが他に存在しない場合** _`alt`属性には画像内の文言を含めてください。詳細：[[文字画像]](/tutorials/images/textual/#styled-text-decorative-effect)_
Original text: 
> … and the text in the image is not present otherwise.

My automatic translation tool translates your version into "and there is no other text in the image".

If so, can you please find a translation closer to the original meaning? This refers in particular to images of text, such as bitmap images to present headings in a particular font that is not widely deployed. In that situation, "the text in the image is not present otherwise".

2024-02-26 15:28 UTC, remibetin commented on content/images/decision-tree.ja.md
> +  - {:.yes} この決定木はすべてのケースをカバー**しているわけではありません**。代替テキストの提供に関する詳細については、「[画像に関する概念ページ](/tutorials/images/)」を参照してください。
> Do you know why the text here is different from the actual page name?

I do not know. I have opened an issue https://github.com/w3c/wai-tutorials/issues/753

2024-02-26 15:28 UTC, remibetin commented on content/images/decision-tree.ja.md
> +title_html: "代替テキスト決定木"
@hiroya-uga If possible, I think best to keep the original approach in the translation. 

This is a basically a decision tree for the "alt" element, which explains the use of `<code>alt</code>` in the title

2024-02-26 15:28 UTC, remibetin commented on content/images/decision-tree.ja.md
> +  - name: "Uga, Hiroya"
@hiroya-uga I would suggest using "Hiroya Uga", because the different translators are separated with commas in the translation box.

2024-02-26 15:28 UTC, remibetin commented on content/images/decision-tree.ja.md
> +contributors:
Lines 12-13 are redundant with line 10-11, since you are already listed as a translator. The contributors list is mainly used to acknowledge contributions from reviewers.

2024-02-26 15:28 UTC, remibetin commented on content/images/decision-tree.ja.md
> +  - see <a href="/WAI/tutorials/acknowledgements/">Acknowledgements</a>
@hiroya-uga Can you please translate the content in `contributors` and `support` (please leave the acronyms in English though).

2024-02-27 01:06 UTC, hiroya-uga commented on content/images/decision-tree.ja.md
> +title_html: "代替テキスト決定木"
@remibetin I see! I will fix it.

2024-02-27 01:11 UTC, hiroya-uga commented on content/images/decision-tree.ja.md
> +  - see <a href="/WAI/tutorials/acknowledgements/">Acknowledgements</a>
@remibetin I did it!

2024-02-27 01:14 UTC, hiroya-uga commented on content/images/decision-tree.ja.md
> +    - **かつ、画像内のテキストが他に存在しない場合** _`alt`属性には画像内の文言を含めてください。詳細：[[文字画像]](/tutorials/images/textual/#styled-text-decorative-effect)_
@remibetin Sorry, I was misunderstanding. I fixed it!

To-Be
> 画像内のテキストはそれ以外の場所には存在しません

2024-02-27 01:15 UTC, hiroya-uga commented on content/images/decision-tree.ja.md
> +contributors:
I removed it!

2024-02-27 01:16 UTC, hiroya-uga commented on content/images/decision-tree.ja.md
> +  - name: "Uga, Hiroya"
I changed to "Hitoya UGA"

2024-02-27 01:17 UTC, hiroya-uga commented
@remibetin 
> I will now ask some native Japanese reviewers if they can add their comments. If you know some people that might be willing to help, you can also let me know by email.

Yes, I know! I will send you the email!

2024-02-27 02:30 UTC, hiroya-uga commented
@remibetin 
I would like to introduce @momdo.
He is my friend who are active to translate WHATWG's HTML and other specs of web into Japanese.
https://github.com/momdo/momdo.github.io/wiki

I have confirmed that I can request a review from him. 
How about it?

2024-02-27 02:33 UTC, hiroya-uga commented on content/images/decision-tree.ja.md
> +title_html: "代替テキスト決定木"
It is done!

2024-02-27 02:34 UTC, hiroya-uga commented on content/images/decision-tree.ja.md
> +  - {:.yes} この決定木はすべてのケースをカバー**しているわけではありません**。代替テキストの提供に関する詳細については、「[画像に関する概念ページ](/tutorials/images/)」を参照してください。
I changed to "画像チュートリアル" (Image Tutorial)

2024-02-27 09:43 UTC, remibetin commented on content/images/decision-tree.ja.md
> +support: Education and Outreach Working Group（<a href="https://www.w3.org/groups/wg/eowg">EOWG</a>）によって開発されました。このプロジェクトは<a href="https://www.w3.org/WAI/ACT/">WAI-ACTプロジェクト</a>の支援を受けて開発され、<strong>欧州委員
@hiroya-uga Would you please translate the Working Group name?

> Education and Outreach Working Group

2024-02-27 09:43 UTC, remibetin commented on content/images/decision-tree.ja.md
> +  - 詳細：<a href="/WAI/tutorials/acknowledgements/">Acknowledgements</a>
@hiroya-uga "Acknowledgements" needs translation.

2024-02-27 09:55 UTC, remibetin commented
> @remibetin I would like to introduce @momdo. 
> I have confirmed that I can request a review from him. How about it?

Sure, @momdo is welcome to participate in the review! 

Thank you @momdo! For information on reviewing WAI translations, please read the following documents:
- [WAI Translations Policy](https://www.w3.org/WAI/about/translating/#important-notes)
- [Guide - Reviewing a Translation](https://www.w3.org/WAI/about/translating/guides/review-translation/)

To confirm your intent, please indicate in the Pull Request the date by which you plan to complete the review.

2024-02-27 13:34 UTC, momdo commented
@remibetin @hiroya-uga 

Thank you for the invitation.
I intend to complete the review by 5 March.

2024-02-28 01:40 UTC, hiroya-uga commented on content/images/decision-tree.ja.md
> +support: Education and Outreach Working Group（<a href="https://www.w3.org/groups/wg/eowg">EOWG</a>）によって開発されました。このプロジェクトは<a href="https://www.w3.org/WAI/ACT/">WAI-ACTプロジェクト</a>の支援を受けて開発され、<strong>欧州委員
@remibetin I fixed!

```diff
- Education and Outreach Working Group（<a href="https://www.w3.org/groups/wg/eowg">EOWG</a>）
+ 教育・啓発ワーキンググループ（<a href="https://www.w3.org/groups/wg/eowg"><abbr title="Education and Outreach Working Group">EOWG</abbr></a>）
```

2024-02-28 01:40 UTC, hiroya-uga commented on content/images/decision-tree.ja.md
> +  - 詳細：<a href="/WAI/tutorials/acknowledgements/">Acknowledgements</a>
@remibetin I did it!

```diff
-   - 詳細：<a href="/WAI/tutorials/acknowledgements/">Acknowledgements</a>
+   - 詳細：<a href="/WAI/tutorials/acknowledgements/">謝辞</a>
```

2024-03-03 05:02 UTC, momdo reviewed
@hiroya-uga @remibetin 
Review completed. Please let me know if you have any questions.

2024-03-03 05:02 UTC, momdo commented on content/images/decision-tree.ja.md
> +この決定木（ディシジョンツリー）は、`<img>`要素の`alt`属性の使い方を状況に合わせて説明するためのものです。装飾目的の画像の代わりにCSS背景画像を用いたり、文字画像の代わりにWebフォントを利用するなど、一部の画像の種類には代替手段が存在します。
The phrase [in various situations](https://eow.alc.co.jp/search?q=in+various+situations) suggests the translation phrase "さまざまな状況で".

The current structure of translation is "決定木（中略）は、～説明するためのものです。".
I would suggest the following translation:
決定木（中略）では、～説明します。
決定木（中略）は、～説明するものです。

Make concord with the word "たり". So:
～用いたり、...利用したりする

I could suggest the translation phrase "画像の種類によっては、" for the phrase "For some types of images,", and put the phrase at the beginning of a sentence.

2024-03-03 05:02 UTC, momdo commented on content/images/decision-tree.ja.md
> +      _空の`alt`属性を利用してください。詳細：[[装飾目的の画像]](/tutorials/images/decorative/)_
How about the following structure?

```markdown
空の`alt`属性を利用します。詳細は[[装飾目的の画像]](/tutorials/images/decorative/)を参照してください。_
```

It would be my recommendation to avoid using the symbol "：" in accordance with the original text.

In the immediately preceding sentence, the word "text" is translated as "文字", but in this sentence the translation is as follows:
「その文言」「実際のテキスト」。

We need to unify all translation words of the word "text", excluding the words "images of text", on this page.

2024-03-03 05:02 UTC, momdo commented on content/images/decision-tree.ja.md
> +      _`alt`属性を、画像の機能を伝えるために用いてください。詳細：[[機能を持つ画像]](/tutorials/images/functional/)_
We need to unify the translation word of the word "use" on this tree.

2024-03-03 05:02 UTC, momdo commented on content/images/decision-tree.ja.md
> +    - **かつ、画像内のテキストがそれ以外の場所に存在しない場合** _`alt`属性には画像内の文言を含めてください。詳細：[[文字画像]](/tutorials/images/textual/#styled-text-decorative-effect)_
Explicitly translate the word "the", like this:

```suggestion
    - **かつ、画像内のテキストがそれ以外の場所に存在しない場合** _`alt`属性にはその画像内の文言を含めてください。詳細：[[文字画像]](/tutorials/images/textual/#styled-text-decorative-effect)_
```

2024-03-03 05:02 UTC, momdo commented on content/images/decision-tree.ja.md
> +- **その画像はリンクまたはボタンの中で使用されていますか？また、画像が存在しない場合はリンクやボタンがどのような動作をするか理解することが困難あるいは不可能ですか？**
For clarity, I would suggest that the word "or" is basically translated as "または".

2024-03-03 05:02 UTC, momdo commented on content/images/decision-tree.ja.md
> +- **その画像の用途は前述の一覧にないですか？またはどのような代替テキストを提供するべきか曖昧ですか？**
Machine translation ([みんなの自動翻訳](https://mt-auto-minhon-mlt.ucri.jgn-x.jp/)) offers the following suggestions:

```suggestion
- **その画像の用途は上記に記載されていないですか？またはどのような代替テキストを提供するべきか不明ですか？**
```

2024-03-03 05:02 UTC, momdo commented on content/images/decision-tree.ja.md
> +  - {:.yes} この決定木はすべてのケースをカバーしているわけでは**ありません**。代替テキストの提供に関する詳細については、「[画像チュートリアル](/tutorials/images/)」を参照してください。
I would suggest the translation word "網羅する" for the word "cover".

2024-03-03 17:58 UTC, hiroya-uga commented on content/images/decision-tree.ja.md
> +- **その画像はリンクまたはボタンの中で使用されていますか？また、画像が存在しない場合はリンクやボタンがどのような動作をするか理解することが困難あるいは不可能ですか？**
I resolved: https://github.com/w3c/wai-tutorials/pull/752/commits/c70b7d87c66558b2506a5fb5163d5210156ac8ad

2024-03-03 17:58 UTC, hiroya-uga commented on content/images/decision-tree.ja.md
> +      _`alt`属性を、画像の機能を伝えるために用いてください。詳細：[[機能を持つ画像]](/tutorials/images/functional/)_
I resolved: https://github.com/w3c/wai-tutorials/pull/752/commits/222dd44879705d978cde19e2bf4b6cef61e27088

2024-03-03 17:59 UTC, hiroya-uga commented on content/images/decision-tree.ja.md
> +  - {:.yes} この決定木はすべてのケースをカバーしているわけでは**ありません**。代替テキストの提供に関する詳細については、「[画像チュートリアル](/tutorials/images/)」を参照してください。
Fixed! https://github.com/w3c/wai-tutorials/pull/752/commits/17583cfd70c0684126cb4f283e4e6f08ff8919e6

2024-03-03 18:08 UTC, hiroya-uga commented on content/images/decision-tree.ja.md
> +この決定木（ディシジョンツリー）は、`<img>`要素の`alt`属性の使い方を状況に合わせて説明するためのものです。装飾目的の画像の代わりにCSS背景画像を用いたり、文字画像の代わりにWebフォントを利用するなど、一部の画像の種類には代替手段が存在します。
I fixed!
https://github.com/w3c/wai-tutorials/pull/752/commits/31f22a88769ba30a5d6cc7c17a6bf4a013d32698

2024-03-03 18:12 UTC, hiroya-uga commented on content/images/decision-tree.ja.md
> +      _空の`alt`属性を利用してください。詳細：[[装飾目的の画像]](/tutorials/images/decorative/)_
> 空の`alt`属性を利用します。詳細は[[装飾目的の画像]](/tutorials/images/decorative/)を参照してください。


I felt a strong sense of discomfort with consecutive uses of "ください" in Japanese and was considering other expressions.
But I was unsure if the Japanese phrase "利用します" (using/using it) is correct as a phrase that prompts action in documents like guidelines. This feedback was very helpful.
Thank you!!

2024-03-03 18:22 UTC, hiroya-uga commented on content/images/decision-tree.ja.md
> +      _空の`alt`属性を利用してください。詳細：[[装飾目的の画像]](/tutorials/images/decorative/)_
I was concerned that having the word "テキスト" repeated consecutively would make the sentence difficult to read. However, I now understand that this is unavoidable in the translation of technical guidelines.

It's all fixed now!

→ https://github.com/w3c/wai-tutorials/pull/752/commits/ee0b3f3958dee4d144dca72bf167904a8af071d9

2024-03-03 18:23 UTC, hiroya-uga commented
@momdo cc: @remibetin 
Thank you for the review! I have made all the corrections. Could you please review them? :^)
https://deploy-preview-752--wai-tutorials2.netlify.app/tutorials/images/decision-tree/ja

2024-03-03 18:34 UTC, hiroya-uga commented on content/images/decision-tree.ja.md
> +      _意味が伝わるように画像の簡単な説明を`alt`属性値に利用します。詳細は[[意味のある画像]](/tutorials/images/informative/)を参照してください。_
![ask](https://img.shields.io/badge/review-ask-blue.svg)
@remibetin cc: @momdo 

When translating, I often feel the urge to insert a line break when the Japanese version becomes two sentences are bit long.
Is this practice not advisable in the translation works?

```suggestion
      _意味が伝わるように画像の簡単な説明を`alt`属性値に利用します。<br>詳細は[[意味のある画像]](/tutorials/images/informative/)を参照してください。_
```

2024-03-03 18:39 UTC, hiroya-uga commented on content/images/decision-tree.ja.md
> +      _意味が伝わるように画像の簡単な説明を`alt`属性値に利用します。詳細は[[意味のある画像]](/tutorials/images/informative/)を参照してください。_
* [In the fact](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-br-element), using the `<br>` element like this is not recommended, but...

2024-03-04 10:35 UTC, remibetin commented on content/images/decision-tree.ja.md
> +      _意味が伝わるように画像の簡単な説明を`alt`属性値に利用します。詳細は[[意味のある画像]](/tutorials/images/informative/)を参照してください。_
@hiroya-uga Indeed, it is generally not advisable to adapt the code, unless there is a strong motive. 

For example, if necessary for the content to be properly understood in the targeted language. From your message, it seems to me this is not one of those cases, or is it?

2024-03-04 13:00 UTC, momdo commented on content/images/decision-tree.ja.md
> +- **その画像はリンクまたはボタンの中で使用されていますか？また、画像が存在しない場合はリンクやボタンがどのような動作をするか理解することが困難あるいは不可能ですか？**
Thank you for accepting my suggestion, but the translated word "あるいは" remains unchanged.

2024-03-04 13:23 UTC, momdo commented on content/images/decision-tree.ja.md
> +      _意味が伝わるように画像の簡単な説明を`alt`属性値に利用します。詳細は[[意味のある画像]](/tutorials/images/informative/)を参照してください。_
@hiroya-uga 
My understanding is that the `<br>` topic is the same as the symbol `：` topic.

2024-03-04 14:03 UTC, remibetin commented on content/images/decision-tree.ja.md
> +  - {:.yes} この決定木はすべてのケースをカバー**しているわけではありません**。代替テキストの提供に関する詳細については、「[画像に関する概念ページ](/tutorials/images/)」を参照してください。
@hiroya-uga Until the issue is resolved, please keep the original wording for now. I will let you know if this is changed in the future.

2024-03-04 14:10 UTC, hiroya-uga commented on content/images/decision-tree.ja.md
> +      _意味が伝わるように画像の簡単な説明を`alt`属性値に利用します。詳細は[[意味のある画像]](/tutorials/images/informative/)を参照してください。_
@remibetin @momdo 
Thank you for explaining!

I was concerned about is the translated sentences is easy to read in Japanese. 
However, I understood that this concern is not important so much for the task of "translation."

My mission is to avoid "Japanese that cannot be understood" and to stick as closely to the original text as possible. 
I will continue to contribute!:tada:

2024-03-04 14:13 UTC, hiroya-uga commented on content/images/decision-tree.ja.md
> +- **その画像はリンクまたはボタンの中で使用されていますか？また、画像が存在しない場合はリンクやボタンがどのような動作をするか理解することが困難あるいは不可能ですか？**
Oh, I updated now!!
https://github.com/w3c/wai-tutorials/pull/752/commits/8c4425144580536858b773ae3fedec1604ca2cf9

2024-03-04 14:16 UTC, hiroya-uga commented on content/images/decision-tree.ja.md
> +  - {:.yes} この決定木はすべてのケースをカバー**しているわけではありません**。代替テキストの提供に関する詳細については、「[画像に関する概念ページ](/tutorials/images/)」を参照してください。
@remibetin Ok!
I reverted!
https://github.com/w3c/wai-tutorials/pull/752/commits/9999b24ec8b3ffba3b437927a1f06a6b6cb7fec1

2024-03-04 14:20 UTC, momdo commented
@hiroya-uga 
I looked at the demo page and thought, the current heading text is "alt決定木," but does it look good? And when you read it aloud, how does it make you feel?
It's a matter of personal preference, I feel like calling it "altデシジョンツリー" a little bit.

2024-03-04 14:26 UTC, remibetin commented
@momdo Considering your contribution to the review, I think right to make your name appear as "Contributor" to the translation. Let me know how you would like to see your name written.

2024-03-04 14:28 UTC, hiroya-uga commented
>I looked at the demo page and thought, the current heading text is "alt決定木," but does it 
 look good? And when you read it aloud, how does it make you feel?
> It's a matter of personal preference, I feel like calling it "altデシジョンツリー" a little bit.

@momdo 決定木 is like 決定キー 🙃
Of course, I wonted to use "ディシジョンツリー".

But I did not know whether it is famous or not...
So, I'm glad for this advice!

I changed to "ディシジョンツリー"!🎉


fyi:

**決定木**
<img width="722" alt="image" src="https://github.com/w3c/wai-tutorials/assets/46584540/01891025-9da3-482c-91d6-041352f9e6f0">


**ディシジョンツリー**
<img width="739" alt="image" src="https://github.com/w3c/wai-tutorials/assets/46584540/4d287d16-b4e6-4d10-9cea-a52317a6b147">

**デシジョンツリー**
<img width="728" alt="image" src="https://github.com/w3c/wai-tutorials/assets/46584540/87c8f0d4-894c-4164-9053-eba4a00c061c">

2024-03-04 23:56 UTC, momdo commented
@hiroya-uga 
Thank you so much. Looks good to me. 

@remibetin 
I'm grateful for your offer.
I would like to display the following name:
Naoki Nakamura

2024-03-05 01:11 UTC, hiroya-uga commented
@momdo Thank you！ Would you [check approve](https://qiita.com/YumaInaura/items/8223add6d8335a2eda7f)?

@remibetin I added the name of momdo into contributors! https://github.com/w3c/wai-tutorials/pull/752#issuecomment-1977692734:~:text=Verified-,31b5b35,-Merge%20state

2024-03-05 09:31 UTC, momdo approved these changes

2024-03-05 09:33 UTC, remibetin approved these changes

2024-03-05 09:39 UTC, remibetin commented
Thank you @hiroya-uga @momdo for your collaborative work! 🎉 

We will publish the translation very soon.

2024-03-05 14:28 UTC, shawna-slh commented
Thank you!

2024-03-05 14:28 UTC, merged

2024-03-05 15:27 UTC, remibetin commented
This translation has been published today 🚀 Thank you @hiroya-uga @momdo!

See https://www.w3.org/WAI/tutorials/images/decision-tree/ja