Translate decision-tree.md to Korean
w3c/wai-tutorials pull request #761
Opened 2024-03-12 11:21 UTC by hwahyeon

Resolves w3c/wai-translations#191

Thanks!

2024-03-26 12:10 UTC, remibetin requested changes
@hwahyeon Thank you for this translation! I have added some comments for your consideration.

To complete the translation, can you also open a PR to add the Korean versions of some UI terms used in the footer of this resource? See [Translation Notes](https://github.com/w3c/wai-tutorials?tab=readme-ov-file#translation-notes)

2024-03-26 12:10 UTC, remibetin commented on content/images/decision-tree.kr.md
> +    - _`alt` 속성을 사용하여 링크의 대상이나 수행되는 작업의 의미를 전달하세요. [기능적 이미지](/tutorials/images/functional/)를 참조하세요._
@hwahyeon My automatic translation tool translates it into "Use the `alt` attribute to convey the meaning of what the link is about or what action is being performed" 

If so, do you think of a closer translation, considering the original version: "Use the alt attribute to communicate **the destination of the link** or action taken"?

2024-03-26 12:10 UTC, remibetin commented on content/images/decision-tree.kr.md
> +  - {:.yes} 이 의사결정나무는 모든 경우를 다루지 않습니다. 대체 텍스트 제공에 대한 자세한 내용은 [이미지 개념 페이지](/tutorials/images/)를 참조하십시오.
@hwahyeon "does not" is in bold in the original version. Can you apply the same styling in the Korean version?

2024-03-26 12:10 UTC, remibetin commented on content/images/decision-tree.kr.md
> +이 의사결정트리는 다양한 상황에서 `<img>` 요소의 `alt` 속성을 사용하는 방법에 대해 설명합니다. 이미지 유형에 따라, 장식용 이미지로 CSS 배경 이미지를 사용하거나 이미지로 된 문자 대신 웹 글꼴을 사용하는 등의 대안이 있습니다.
@hwahyeon 

Original version:
> "For some types of images, there are alternative approaches, such as using CSS background images for decorative images or web fonts instead of images of text."

Draft Korean translation: (automatic translation into English)
> "Depending on the type of image, alternatives include using a CSS background image as a decorative image or using a web font instead of imaged text."

Because things are worded differently, I just want to make sure the meaning is not distorted.

In particular:
- Do you think of a closer translation of "such as using CSS background images for decorative images"? (i.e. in the case of decorative images, not using an `<img>` element and avoiding the question of the `alt` attribute content).
- Can you confirm that your translation of "images of text" refers to images that display text intended to be read (see [Images of Text](https://www.w3.org/WAI/tutorials/images/textual/#styled-text-decorative-effect) for more context on this)

2024-03-26 17:27 UTC, hwahyeon commented on content/images/decision-tree.kr.md
> +이 의사결정트리는 다양한 상황에서 `<img>` 요소의 `alt` 속성을 사용하는 방법에 대해 설명합니다. 이미지 유형에 따라, 장식용 이미지로 CSS 배경 이미지를 사용하거나 이미지로 된 문자 대신 웹 글꼴을 사용하는 등의 대안이 있습니다.
@remibetin 

- If I had to translate my translation back into English literally, it would look like this :

> Depending on the type of image, there are alternatives(대안이 있습니다), such as(등의) using CSS background images as decorative images or using web fonts instead of images of text.

- I think `images of text` has been translated into Korean with the right meaning.

If there are any other issues, please let me know

2024-03-26 17:31 UTC, hwahyeon commented on content/images/decision-tree.kr.md
> +    - _`alt` 속성을 사용하여 링크의 대상이나 수행되는 작업의 의미를 전달하세요. [기능적 이미지](/tutorials/images/functional/)를 참조하세요._
@remibetin 
I corrected this translation for clarity

thanks!

2024-03-26 17:36 UTC, remibetin commented on content/images/decision-tree.kr.md
> +이 의사결정트리는 다양한 상황에서 `<img>` 요소의 `alt` 속성을 사용하는 방법에 대해 설명합니다. 이미지 유형에 따라, 장식용 이미지로 CSS 배경 이미지를 사용하거나 이미지로 된 문자 대신 웹 글꼴을 사용하는 등의 대안이 있습니다.
Thanks for the clarification @hwahyeon!

2024-03-26 17:55 UTC, hwahyeon commented
@remibetin 

I opened a PR: https://github.com/w3c/wai-website-data/pull/139

thanks!

2024-04-04 14:43 UTC, remibetin approved these changes

2024-04-04 19:18 UTC, merged

2024-04-08 15:56 UTC, remibetin commented
QA done: OK ✅